baseURL = 'https://Mr615-TN.github.io/Tanish_Portfolio/'
languageCode = 'en-us'
title = "Tanish Neema : The Portfolio"
theme = "ananke"
[params]
new_window = true 
    [params.profile]
    show_reading_time = true 
        [params.anake.social]
            networks = [ "instagram","github", "linkedin"]

            [params.anake.social.instagram]
                username = "i_found_nemo1256"

            [params.anake.social.github]
                username = "Mr615-TN"

            [params.anake.social.linkedin]
                username = "Tanish Neema"

